#!/bin/bash - 
#===============================================================================
#
#          FILE: touchpadctrl
# 
#         USAGE: ./touchpadctrl 
# 
#   DESCRIPTION: 
# 
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: linkscue (scue), linkscue@gmail.com
#  ORGANIZATION: 
#       CREATED: 2014年03月09日 12时57分34秒 CST
#      REVISION:  ---
#===============================================================================

# xinput --list             ==> 获取TouchPad的id号(我的是12)
# xinput --list-props 12    ==> 获取TouchPad的设备状态
# man xinput                ==> 获取xinput的使用方法
on(){
    #synclient  TouchpadOff=0
    xinput set-prop 12 'Device Enabled' 1
    echo -e "\e[0;36mtouchpad on.\e[0m" # cyan
    exit
}
off(){
    #synclient TouchpadOff=1
    xinput set-prop 12 'Device Enabled' 0
    echo -e "\e[0;36mtouchpad off.\e[0m" # cyan
    exit
}

usage(){
    echo -e "\e[0;31m==> Usage: $(basename $0) [ON/off/toggle].\e[0m" # red
    exit
}

getstate(){
    echo $(xinput --list-props 12 | grep Enable | awk -F: '{print $2}')
}

toggle(){
    echo -en "\e[0;31m==> toggle: \e[0m" # red
    case $(getstate) in
        "0" ) on
            ;;
        "1" ) off
            ;;
    esac
}

# detect: help
if [[ ${1} != "" ]]; then
    case ${1} in
        "-h" | "--help" | "-help" )
            usage
            ;;
    esac
fi

if [[ $# == 0 ]]; then
    # auto swtich
    if [[ $(lsusb | grep 'Sunplus Innovation Technology') != "" ]]; then
        off
    else
        toggle
    fi
else
    # manual
    case ${1} in
        "of"|"off"|"OFF"|"Off") off
            ;;
        "t"|"toggle"|"T"|"Toggle") toggle
            ;;
        *) on 
            ;;
    esac
fi
